version: '3.9'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drogariav3
    ports:
      - 3306:3306
    networks:
      - drogariav3-network
networks:
  drogariav3-network:
    driver: bridge
